name: ai-sast-workflow

on:
  push:
    branches:
      - dev
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: ayvazbudapeshtov/ai-sast-tool:1.0.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Run ai-sast-tool
      run: python3.12 main.py .
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    - name: Upload report.html
      uses: actions/upload-artifact@v4
      with:
          name: report
          path: report.html

  ngrok-up:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - name: Download report artifact
      uses: actions/download-artifact@v4
      with:
        name: report
        path: ./
    - name: Start HTTP server and ngrok
      run: |
        # Start httpd server and mount the current directory to serve your HTML file
        docker run -d --name httpd-server -v ${{ github.workspace }}:/usr/local/apache2/htdocs/ httpd:2.4
        # Start ngrok
        docker run -d --name ngrok --link httpd-server -p 4040:4040 wernight/ngrok ngrok http httpd-server:80
    - name: Wait for ngrok
      run: |
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4040)" != "200" ]]; do sleep 5; done'
