name: ai-sast-workflow

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ayvazbudapeshtov/ai-sast-tool:1.0.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Run ai-sast-tool
      run: python3.12 main.py .
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    - name: Upload juice-shop.html
      uses: actions/upload-artifact@v4
      with:
          name: juice-shop
          path: juice-shop.html