name: Build, Tag, Push and Sign Docker Image

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Tag, Push, and Sign Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: image_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "::set-output name=tag::latest"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=tag::dev"
          elif [[ ${{ github.ref }} =~ refs/tags/v(.*) ]]; then
            VERSION=${BASH_REMATCH[1]}
            echo "::set-output name=tag::$VERSION"
          else
            echo "::set-output name=tag::commit-${{ github.sha }}"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ai-sast-tool:${{ steps.image_tag.outputs.tag }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ai-sast-tool:${{ steps.image_tag.outputs.tag }}
      - name: Log out from Docker Hub
        run: docker logout
