name: Build, Tag, Push and Sign Docker Image

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Tag, Push, and Sign Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag
        id: image_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" =~ refs/tags/v(.*) ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -E 's/refs\/tags\/v(.*)/\1/')
            echo "tag=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "tag=commit-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ai-sast-tool:${{ steps.image_tag.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ai-sast-tool:${{ steps.image_tag.outputs.tag }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: 'v2.4.0'

      - name: Sign Docker image with Cosign (keyless)
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: |
          cosign sign ${{ secrets.DOCKERHUB_USERNAME }}/ai-sast-tool:${{ steps.image_tag.outputs.tag }}

      - name: Log out from Docker Hub
        run: docker logout
